const higherInstitutionsInNigeria = [
	{ id: 0, name: 'Achievers University, Owo' },
	{ id: 1, name: 'Adeleke University, Ede' },
	{ id: 2, name: 'Afe Babalola University, Ado-Ekiti' },
	{ id: 3, name: 'African University of Science &amp; Technology' },
	{ id: 4, name: 'Ajayi Crowther University, Ibadan' },
	{ id: 5, name: 'Al-Hikmah University, Ilorin' },
	{ id: 6, name: 'Al-Qalam University' },
	{ id: 7, name: 'American University of Nigeria, Yola' },
	{ id: 8, name: 'Augustine University' },
	{ id: 9, name: 'Babcock University,Ilishan-Remo' },
	{ id: 10, name: 'Baze University' },
	{ id: 11, name: 'Bells University of Technology, Otta' },
	{ id: 12, name: 'Benson Idahosa University, Benin City' },
	{ id: 13, name: 'Bingham University, New Karu' },
	{ id: 14, name: 'Bowen University, Iwo' },
	{ id: 15, name: 'Caleb University, Lagos' },
	{ id: 16, name: 'Caritas University' },
	{ id: 17, name: 'CETEP City University' },
	{ id: 18, name: 'Chrisland University' },
	{ id: 19, name: 'Christopher University Mowe' },
	{ id: 20, name: 'Covenant University Ota' },
	{ id: 21, name: 'Crawford University Igbesa' },
	{ id: 22, name: 'Crescent University' },
	{ id: 23, name: 'Edwin Clark University, KaIgbodo' },
	{ id: 24, name: 'Elizade University, Ilara-Mokin' },
	{ id: 25, name: 'Evangel University, Akaeze' },
	{ id: 26, name: 'Godfrey Okoye University, Ugwuomu-Nike' },
	{ id: 27, name: 'Gregory University, Uturu' },
	{ id: 28, name: 'Hallmark University' },
	{ id: 29, name: 'Hezekiah University, Umudi' },
	{ id: 30, name: 'Igbinedion University Okada' },
	{ id: 31, name: 'Joseph Ayo Babalola University, Ikeji-Arakeji' },
	{ id: 32, name: 'Kings University' },
	{ id: 33, name: 'Kwararafa University, Wukari' },
	{ id: 34, name: 'Landmark University, Omu-Aran.' },
	{ id: 35, name: 'Lead City University, Ibadan' },
	{ id: 36, name: 'Madonna University, Okija' },
	{ id: 37, name: 'Mcpherson University, Seriki Sotayo, Ajebo' },
	{ id: 38, name: 'Micheal &amp; Cecilia University' },
	{ id: 39, name: 'Mountain Top University' },
	{ id: 40, name: 'Nigerian-Turkish Nile University' },
	{ id: 41, name: 'Novena University, Ogume' },
	{ id: 42, name: 'Obong University, Obong Ntak' },
	{ id: 43, name: 'Oduduwa University, Ipetumodu' },
	{ id: 44, name: 'Pan-Atlantic University, Lagos' },
	{ id: 45, name: 'Paul University, Awka' },
	{ id: 46, name: "Redeemer's University, Mowe" },
	{ id: 47, name: 'Renaissance University' },
	{ id: 48, name: 'Rhema University, Obeama-Asa' },
	{ id: 49, name: 'Ritman University' },
	{ id: 50, name: 'Salem University, Lokoja' },
	{ id: 51, name: 'Samuel Adegboyega University, Ogwa.' },
	{ id: 52, name: 'Southwestern University, Oku Owa' },
	{ id: 53, name: 'Summit University' },
	{ id: 54, name: 'Tansian University, Umunya' },
	{ id: 55, name: 'University of Mkar, Mkar' },
	{ id: 56, name: 'Veritas University' },
	{ id: 57, name: 'Wellspring University, Evbuobanosa' },
	{ id: 58, name: 'Wesley University. of Science &amp; Technology, Ondo' },
	{ id: 59, name: 'Western Delta University, Oghara ' },
	{ id: 60, name: 'Abubakar Tafawa Balewa University, Bauchi' },
	{ id: 61, name: 'Ahmadu Bello University, Zaria' },
	{ id: 62, name: 'Bayero University, Kano' },
	{ id: 63, name: 'Federal University Gashua' },
	{ id: 64, name: 'Federal University of Agriculture, Abeokuta' },
	{ id: 65, name: 'Federal University of Petroleum Resources, Effurun' },
	{ id: 66, name: 'Federal University of Technology, Akure' },
	{ id: 67, name: 'Federal University of Technology, Minna' },
	{ id: 68, name: 'Federal University of Technology, Owerri' },
	{ id: 69, name: 'Federal University, Birnin Kebbi' },
	{ id: 70, name: 'Federal University, Dutse.' },
	{ id: 71, name: 'Federal University, Dutsin-Ma' },
	{ id: 72, name: 'Federal University, Gusau ' },
	{ id: 73, name: 'Federal University, Kashere' },
	{ id: 74, name: 'Federal University, Lafia.' },
	{ id: 75, name: 'Federal University, Lokoja.' },
	{ id: 76, name: 'Federal University, Ndifu-Alike.' },
	{ id: 77, name: 'Federal University, Otuoke' },
	{ id: 78, name: 'Federal University, Oye-Ekiti.' },
	{ id: 79, name: 'Federal University, Wukari.' },
	{ id: 80, name: 'Michael Okpara University of Agriculture, Umudike' },
	{ id: 81, name: 'Modibbo Adama University of Technology, Yola' },
	{ id: 82, name: 'National Open University of Nigeria.' },
	{ id: 83, name: 'University of Ilorin' },
	{ id: 84, name: 'Nnamdi Azikiwe University, Awka' },
	{ id: 85, name: 'Obafemi Awolowo University,Ile-Ife' },
	{ id: 86, name: 'University of Abuja, Gwagwalada' },
	{ id: 87, name: 'University of Agriculture, Makurdi' },
	{ id: 88, name: 'University of Benin' },
	{ id: 89, name: 'University of Calabar' },
	{ id: 90, name: 'University of Ibadan' },
	{ id: 91, name: 'University of Jos' },
	{ id: 92, name: 'University of Lagos' },
	{ id: 93, name: 'University of Maiduguri' },
	{ id: 94, name: 'University of Nigeria, Nsukka' },
	{ id: 95, name: 'University of Port-Harcourt' },
	{ id: 96, name: 'University of Uyo' },
	{ id: 97, name: 'Usumanu Danfodiyo University' },
	{ id: 98, name: 'Abia State University, Uturu' },
	{ id: 99, name: 'Adamawa State University Mubi' },
	{ id: 100, name: 'Adekunle Ajasin University, Akungba' },
	{ id: 100, name: 'Adekunle Ajasin University, Akungba' },
	{ id: 101, name: 'Akwa Ibom State University of Technology, Uyo' },
	{ id: 102, name: 'Ambrose Alli University, Ekpoma' },
	{ id: 103, name: 'Bauchi State University, Gadau' },
	{ id: 104, name: 'Benue State University, Makurdi' },
	{ id: 105, name: 'Bukar Abba Ibrahim University, Damaturu' },
	{ id: 106, name: 'Chukwuemeka Odumegwu Ojukwu University, Uli' },
	{ id: 107, name: 'Cross River State University of Science &amp;Technology, Calabar' },
	{ id: 108, name: 'Delta State University Abraka' },
	{ id: 109, name: 'Eastern Palm University Ogboko, Imo State ' },
	{ id: 110, name: 'Ebonyi State University, Abakaliki ' },
	{ id: 111, name: 'Edo University Iyamo ' },
	{ id: 112, name: 'Ekiti State University' },
	{ id: 113, name: 'Enugu State University of Science and Technology.' },
	{ id: 114, name: 'Ibrahim Badamasi Babangida University, Lapai ' },
	{ id: 115, name: 'Ignatius Ajuru University of Education,Rumuolumeni' },
	{ id: 116, name: 'Imo State University, Owerri' },
	{ id: 117, name: 'Kaduna State University' },
	{ id: 118, name: 'Kano University of Science &amp; Technology, Wudil' },
	{ id: 119, name: 'Kebbi State University, ' },
	{ id: 120, name: 'Kogi State University Anyigba' },
	{ id: 121, name: 'Kwara State University, Ilorin' },
	{ id: 122, name: 'Ladoke Akintola University of Technology, Ogbomoso' },
	{ id: 123, name: 'Lagos State University, Ojo' },
	{ id: 124, name: 'Nasarawa State University Keffi' },
	{ id: 125, name: 'Niger Delta University Yenagoa' },
	{ id: 126, name: 'Northwest University Kano' },
	{ id: 127, name: 'Olabisi Onabanjo University, Ago Iwoye' },
	{ id: 128, name: 'Ondo State University of Medical Sciences' },
	{ id: 129, name: 'Ondo State University of Science and Technology Okitipupa' },
	{ id: 130, name: 'Osun State University Osogbo' },
	{ id: 131, name: 'Oyo State Technical University Ibadan' },
	{ id: 132, name: 'Plateau State University Bokkos' },
	{ id: 133, name: 'River State University of Science and Technology' },
	{ id: 134, name: 'Sokoto State University' },
	{ id: 135, name: 'Sule Lamido University, Kafin Hausa, Jigawa' },
	{ id: 136, name: 'Tai Solarin University of Education Ijebu Ode' },
	{ id: 138, name: 'Taraba State University, Jalingo' },
	{ id: 139, name: "Umar Musa Yar' Adua University Katsina" },
	{ id: 140, name: 'Yaba College of Technology' },
	{ id: 141, name: 'Colleges of Education in Nigeria' },
	{ id: 142, name: 'Adamawa State College of Education' },
	{ id: 143, name: 'Adamu Augie College of Education' },
	{ id: 144, name: 'Adeniran Ogunsanya College of Education' },
	{ id: 145, name: 'Adeyemi College of Education' },
	{ id: 146, name: 'Akwa-Ibom State College of Art &amp; Science' },
	{ id: 147, name: 'Akwa-Ibom State College of Education' },
	{ id: 148, name: 'Ansar Ud Deen College of Education' },
	{ id: 149, name: 'Bayelsa State College of Arts and Science' },
	{ id: 150, name: 'City College of Education' },
	{ id: 151, name: 'College of Education Gashua' },
	{ id: 152, name: 'College of Education katsina-Ala' },
	{ id: 153, name: 'College-of-Education-Arochukwu' },
	{ id: 154, name: 'College of Education Azare' },
	{ id: 155, name: 'College of Education Ekiadolor Benin' },
	{ id: 156, name: 'College of Education Gindiri' },
	{ id: 157, name: 'College of Education Ikere-Ekiti ' },
	{ id: 158, name: 'College of Education Ila Orangun' },
	{ id: 159, name: 'College of Education Jalingo' },
	{ id: 160, name: 'College of Education Lafiagi' },
	{ id: 161, name: 'College of Education Nsukka' },
	{ id: 162, name: 'College of Education Waka BIU' },
	{ id: 163, name: 'College of Education Warri' },
	{ id: 164, name: 'College of Education Zuba' },
	{ id: 165, name: 'College of Technology osun' },
	{ id: 166, name: 'Corner Stone College of Education' },
	{ id: 167, name: 'Cross-River State College of Education' },
	{ id: 168, name: 'Delar College of Education' },
	{ id: 169, name: 'Delta State College of Education' },
	{ id: 170, name: 'Ebonyi State College of Education' },
	{ id: 171, name: 'Edo State College of Education' },
	{ id: 172, name: 'Emmanuel Alayande College of Education' },
	{ id: 173, name: 'Enugu State College of Education' },
	{ id: 174, name: 'Federal College of Education' },
	{ id: 175, name: 'Federal College of Education Abeokuta' },
	{ id: 176, name: 'Federal College of Education Akoka' },
	{ id: 177, name: 'Federal College of Education Asaba' },
	{ id: 178, name: 'Federal College of Education Bichi' },
	{ id: 179, name: 'Federal College of Education Eha Amufu' },
	{ id: 180, name: 'Federal College of Education Gombe' },
	{ id: 181, name: 'Federal College of Education Gusau' },
	{ id: 182, name: 'Federal College of Education Kano' },
	{ id: 183, name: 'Federal College of Education Katsina' },
	{ id: 184, name: 'Federal College of Education Kontagora' },
	{ id: 185, name: 'Federal College of Education Obudu' },
	{ id: 186, name: 'Federal College of Education Okene' },
	{ id: 187, name: 'Federal College of Education Omoku' },
	{ id: 188, name: 'Federal College of Education Oyo' },
	{ id: 189, name: 'Federal College of Education Pankshin' },
	{ id: 190, name: 'Federal College of Education Potiskum' },
	{ id: 191, name: 'Federal College of Education Yola' },
	{ id: 192, name: 'Federal College of Education Zaria' },
	{ id: 193, name: 'Havard Wilson College of Education' },
	{ id: 194, name: 'Isa Kaita College of Education' },
	{ id: 195, name: 'Jamaatu College of Education' },
	{ id: 196, name: 'Jigawa State College of Education' },
	{ id: 197, name: 'Kaduna State College of Education' },
	{ id: 198, name: 'Kashim Ibrahim College of Education' },
	{ id: 199, name: 'Kogi State College of Education' },
	{ id: 200, name: 'Kwara State College of Education' },
	{ id: 201, name: 'lvan Ikoku College of Education' },
	{ id: 202, name: 'Muftau Olanihun College of Education' },
	{ id: 203, name: 'Muhyideen College of Education' },
	{ id: 204, name: 'Nasarrawa State College of Education' },
	{ id: 205, name: 'Niger State College of Education' },
	{ id: 206, name: 'Nwafor Orizu College of Education' },
	{ id: 207, name: 'Osisatech College of Education' },
	{ id: 208, name: 'Osun State College of Education' },
	{ id: 209, name: 'Peaceland College of Education' },
	{ id: 210, name: 'Rivers College of Education' },
	{ id: 211, name: 'Saadatu Rimi College of Education' },
	{ id: 212, name: 'Shehu shagari College of Education' },
	{ id: 213, name: 'St Augustine College of Education' },
	{ id: 214, name: 'Tai Solarin College of Education' },
	{ id: 215, name: 'Umar Ibn Ibrahim El Kanemi College of Education' },
	{ id: 216, name: 'Zamfara State College of Education' },
	{ id: 217, name: 'African Thinkers Community of Inquiry' },
	{ id: 218, name: 'Airforce Institute of Technology' },
	{ id: 219, name: 'Institute of Ecumenical Education' },
	{ id: 220, name: 'Isaac Jasper Boro' },
	{ id: 221, name: 'Michael Otedola Coll of Prim Education' },
	{ id: 222, name: 'Nigerian Army School of Education' },
	{ id: 223, name: 'Gombe State University' },
	{ id: 224, name: 'Nigerian Defence Academy' },
	{ id: 225, name: 'Nigeria Police Academy Wudil' },
  { id: 226, name: 'Fountain University, Oshogbo' },
  { id: 227, name: 'All Polytechnics in Nigeria' },
	{ id: 228, name: 'Abdu Gusau Polytechnic Talata Mafa' },
	{ id: 229, name: 'Abia State Polytechnic' },
	{ id: 230, name: 'Abraham Adesanya Polytechnic' },
	{ id: 231, name: 'Abubakar Tatari Ali Polytechnic' },
	{ id: 232, name: 'Adamawa State Polytechnic' },
	{ id: 233, name: 'Adegbenro ICT Polytechnic' },
	{ id: 234, name: 'Ajayi Polytechnic' },
	{ id: 235, name: 'Akanu Ibiam Federal Polytechnic Unwana' },
	{ id: 236, name: 'Akwa Ibom State Polytechnic' },
	{ id: 237, name: 'Allover Central Polytechnic' },
	{ id: 238, name: 'Auchi Polytechnic' },
	{ id: 239, name: 'Benue State Polytechnic ' },
	{ id: 240, name: 'Best Solution Polytechnic ' },
	{ id: 241, name: 'Bolmor Polytechnic' },
	{ id: 242, name: 'Calvary Polytechnic' },
	{ id: 243, name: 'Covenant Polytechnic' },
	{ id: 244, name: 'Crown Polytechnic' },
	{ id: 245, name: 'Delta State Polytechnic Otefe Oghara' },
	{ id: 246, name: 'Delta State Polytechnic Ogwashi-Uku' },
	{ id: 247, name: 'Delta State Polytechnic Ozoro' },
	{ id: 248, name: 'Dorben Polytechnic ' },
	{ id: 249, name: 'Eastern Polytechnic' },
	{ id: 250, name: 'Federal Polytechnic Ile-Oluji' },
	{ id: 251, name: 'Federal Polytechnic Ado-Ekiti' },
	{ id: 252, name: 'Federal Polytechnic Bali' },
	{ id: 253, name: 'Federal Polytechnic Bauchi' },
	{ id: 254, name: 'Federal Polytechnic Bida' },
	{ id: 255, name: 'Federal Polytechnic Damaturu' },
	{ id: 256, name: 'Federal Polytechnic Ede' },
	{ id: 257, name: 'Federal Polytechnic Ekowe' },
	{ id: 258, name: 'Federal Polytechnic Idah' },
	{ id: 259, name: 'Federal Polytechnic Ilaro' },
	{ id: 260, name: 'Federal Polytechnic Ile Oluji' },
	{ id: 261, name: 'Federal Polytechnic Kaura Namoda' },
	{ id: 262, name: 'Federal Polytechnic Mubi' },
	{ id: 263, name: 'Federal Polytechnic Nasarawa' },
	{ id: 264, name: 'Federal Polytechnic Nekede' },
	{ id: 265, name: 'Federal Polytechnic Offa' },
	{ id: 266, name: 'Federal Polytechnic of Oil and Gas Bonny' },
	{ id: 267, name: 'Federal Polytechnic Oko' },
	{ id: 268, name: 'Federal-Polytechnic-Ukana' },
	{ id: 269, name: 'Fidei Polytechnic' },
	{ id: 270, name: 'Gateway Polytechnic Saapade' },
	{ id: 271, name: 'Gboko Polytechnic' },
	{ id: 272, name: 'Global Polytechnic' },
	{ id: 273, name: 'Grace Polytechnic' },
	{ id: 274, name: 'Hassan Usman Katsina Polytechnic' },
	{ id: 275, name: 'Heritage Polytechnic' },
	{ id: 276, name: 'Hussaini Adamu Federal Polytechnic' },
	{ id: 277, name: 'Ibadan City Polytechnic' },
	{ id: 278, name: 'Ibarapa Polytechnic Eruwa' },
	{ id: 279, name: 'Igbajo Polytechnic' },
	{ id: 280, name: 'Imo State Polytechnic Umuagwo' },
	{ id: 281, name: 'Interlink Polytechnic' },
	{ id: 282, name: 'Jigawa State Polytechnic Dutse' },
	{ id: 283, name: 'Kaduna Polytechnic' },
	{ id: 284, name: 'Kalac Christal Polytechnic' },
	{ id: 285, name: 'Kano State Polytechnic' },
	{ id: 286, name: 'Ken Sarowiwa Polytechnic' },
	{ id: 287, name: 'Kings Polytechnic' },
	{ id: 288, name: 'Kwara State Polytechnic' },
	{ id: 289, name: 'Lagos City Polytechnic' },
	{ id: 290, name: 'Lagos State Polytechnic Ikorodu' },
	{ id: 291, name: 'Lens Polytechnic' },
	{ id: 292, name: 'Lighthouse Polytechnic' },
	{ id: 293, name: 'Mai Idris Alooma Polytechnic Geidam' },
	{ id: 294, name: 'Marist Polytechnic' },
	{ id: 295, name: 'Moshood Abiola Polytechnic' },
	{ id: 296, name: 'Nacabs Polytechnic' },
	{ id: 297, name: 'Nasarawa State Polytechnic' },
	{ id: 298, name: 'Niger State Polytechnic' },
	{ id: 299, name: 'Nogak Polytechnic' },
	{ id: 300, name: 'Nuhu Bamalli Polytechnic' },
	{ id: 301, name: 'Oke Ogun Polytechnic' },
	{ id: 302, name: 'Osun State Polytechnic' },
	{ id: 303, name: 'Polytechnic Imesi-Ile' },
	{ id: 304, name: 'Polytechnic Otada-Adoka' },
	{ id: 305, name: 'Port Harcourt Polytechnic' },
	{ id: 306, name: 'Prime Polytechnic' },
	{ id: 307, name: 'Ramat Polytechnic' },
	{ id: 308, name: 'Ronik Polytechnic' },
	{ id: 309, name: 'Rufus-Giwa-Polytechnic' },
	{ id: 310, name: 'Shaka Polytechnic' },
	{ id: 311, name: 'St. Mary Polytechnic' },
	{ id: 312, name: 'Sure Foundation Polytechnic' },
	{ id: 313, name: 'Temple Gate Polytechnic' },
	{ id: 314, name: 'The Polytechnic gbo Owu' },
	{ id: 315, name: 'The Polytechnic Ibadan' },
	{ id: 316, name: 'Tower Polytechnic' },
	{ id: 317, name: 'Trinity Polytechnic' },
	{ id: 318, name: 'Umaru-Ali-Shinkafi-Polytechnic' },
	{ id: 319, name: 'Uma Ukpai Polytechnic' },
	{ id: 320, name: 'Uyo City Polytechnic' },
	{ id: 321, name: 'Valley View Polytechnic' },
	{ id: 322, name: 'Waziri Umaru Federal Polytechnic' },
];
